name: Deploy Elastic Geo App

on:
  push:
    branches: ["master"]

jobs:
  build-and-push:
    name: Deploy Elastic Geo App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # backend image
      - name: Build and push backend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: node-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ./node-backend/Dockerfile ./node-backend --target production
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # frontend image
      - name: Build and push frontend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: geo-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ./react-frontend/Dockerfile ./react-frontend --target production
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


      - name: Deploy backend to EKS
        env:
          IMAGE_TAG: ${{ github.sha }}
          KUBE_NAMESPACE: geo-app
        run: |
          sed "s|{{IMAGE_TAG}}|${IMAGE_TAG}|g" ./k8s/backend.yaml | kubectl apply -n $KUBE_NAMESPACE -f -


      - name: Deploy frontend to EKS
        env:
          IMAGE_TAG: ${{ github.sha }}
          KUBE_NAMESPACE: geo-app
        run: |
          sed "s|{{IMAGE_TAG}}|${IMAGE_TAG}|g" ./k8s/frontend.yaml | kubectl apply -n $KUBE_NAMESPACE -f -
