name: Deploy Elastic Geo App

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    name: Build, Push and Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/node-app:$IMAGE_TAG ./node-backend --target production
          docker push $ECR_REGISTRY/node-app:$IMAGE_TAG

      - name: Build and push frontend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/geo-app:$IMAGE_TAG ./react-frontend --target production
          docker push $ECR_REGISTRY/geo-app:$IMAGE_TAG

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name geo-cluster --region ap-south-1

      - name: Deploy backend to EKS
        env:
          IMAGE_TAG: ${{ github.sha }}
          KUBE_NAMESPACE: node-app
        run: |
          aws eks update-kubeconfig --name geo-cluster --region ap-south-1
          sed "s|{{IMAGE_TAG}}|${IMAGE_TAG}|g" ./k8s/backend.yaml | kubectl apply -n $KUBE_NAMESPACE -f -

      - name: Deploy frontend to EKS
        env:
          IMAGE_TAG: ${{ github.sha }}
          KUBE_NAMESPACE: geo-app
        run: |
          aws eks update-kubeconfig --name geo-cluster --region ap-south-1
          sed "s|{{IMAGE_TAG}}|${IMAGE_TAG}|g" ./k8s/frontend.yaml | kubectl apply -n $KUBE_NAMESPACE -f -